<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>login-page</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>

    <div class="container-varification">
    <div class="login-content">
        <form action="index.html">
            <h2 class="title">Change your Password</h2>
            <div class="input-div one">
              <div class="i">
                <i class="fa fa-user"></i>
              </div>
              <div class="div">
                <h5>Old Password</h5>
                <input type="text" class="input" required />
              </div>
            </div>
            <div class="input-div one">
                <div class="i">
                  <i class="fa fa-user"></i>
                </div>
                <div class="div">
                  <h5>New Password</h5>
                  <input type="text" class="input" id="password" required />
                </div>
              </div>
              <div class="input-div one">
                <div class="i">
                  <i class="fa fa-user"></i>
                </div>
                <div class="div">
                  <h5>Confirm New Password</h5>
                  <input type="text" class="input" id="confirmPassword" required />
                </div>
              </div>            
              <span id="message"></span>
            <input type="submit" class="btn" value="Change" />
            
          </form>
          
                   
    </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="core.js"></script>
</body>
</html>