
    <div class="container-varification">
    <div class="login-content">
    <form action="<?php echo $controller ;?>" method="POST" id="form">
            <h2 class="title">Forgot Your Password?</h2>
            <div class="input-div one">
              <div class="i">
                <i class="fa fa-user"></i>
              </div>
              <div class="div">
                <h5>Enter Your E-mail</h5>
                <input type="text" class="input" required />
              </div>
            </div>
              <label class='bg-danger'><?php 
				if(isset($_GET["message"])){
				echo $_GET['message'];
				}
				?></label>
            <input type="button" class="btn" name="sendbtn" value="Send" onclick="submitForm()"/>
            
          </form>
          
                   
    </div>
    </div>
<script>
  function submitForm(form){
    
    var url = $('#form').attr("action");
    
    var formData = $('#form').serializeArray();
    $.post(url, formData).done(function (data) {
        if(data == 1){
      alert('success');
    }else{
      alert('error');
    }
    });
}
</script>