<header>
        <nav>
            
        <div id="menuToggle">
            <input type="checkbox" />
                <span></span>
                <span></span>
                <span></span>
            
            <ul id="menu">
                <a href="#"><li>All Services</li></a>
                <a href="#"><li>Blog</li></a>
                <a href="#"><li>Log Out</li></a>
            </ul>
        </div>
              <!-- end -->

            <div class="logo">
               <a href="#"><img src="<?php echo $image;?>logo.png" alt="demo"></a>
            </div>
            <div class="btn-1-nav">
                <a href="theme/layout/about/about.php">
                    <div class="box-1">
                        <div class="btn btn-one">
                          <span>About</span>
                        </div>
                      </div>
                </a>
                <a href="theme/layout/Contact/contact.html">
                    <div class="box-1">
                        <div class="btn btn-one">
                          <span>Contact</span>
                        </div>
                      </div>
                </a>
                <a href="theme/layout/partners/partners.html">
                    <div class="box-1">
                        <div class="btn btn-one">
                          <span>Partner</span>
                        </div>
                      </div>
                </a>
            </div>
            <div class="btn-2-nav">
                <ul class="learn-dropdown">
                <a href="theme/layout/learn/learn.html" class="nav-nav1">Learn</a>
                <div class="learn-option">
                  <a href="theme/layout/learn-navigation/helpcenter/helpcenter.html" class="learn-select1">Help Center</a>
                  <a href="theme/layout/learn-navigation/videos/videos.html" class="learn-select2">Videos</a>
                  <a href="theme/layout/learn-navigation/customer/customer.html" class="learn-select2">Customer Service</a>
                  <a href="theme/layout/learn-navigation/blog/blog.html" class="learn-select2">Blog/Knowledge Base</a>
                  <a href="theme/layout/learn-navigation/showcase/showcase.html" class="learn-select2">Showcase</a>
                  <a href="theme/layout/learn-navigation/guide/guide.html" class="learn-select3">Guide</a>
                </div>
              </ul>
                <div class="search-box">
                  <input type="text" class="search-txt" placeholder="Search">
                  <button class="search-icon"><span class="icon search"></span></button>
                </div>
            </div>
            <div class="btn-3-nav">
                <div> 
                    
                <a href="?page=login" class="btn btn-sm animated-button thar-login">Login</a>
                <a href="#" class="btn btn-sm animated-button thar-get">Get Started</a> </div>
            </div>
        </nav>
    </header>