<!DOCTYPE html>
<meta name="viewport" content="width=device-width, initial-scale=1">
<head>
	<link rel="stylesheet" type="text/css" href="<?php echo $aosstyle;?>">
	<link rel="stylesheet" type="text/css" href="<?php echo $fonts;?>">
	<link rel="stylesheet" type="text/css" href="<?php echo $stylesheet;?>">
	<link rel="stylesheet" type="text/css" href="<?php echo $substylesheet;?>">
	<link rel="stylesheet" type="text/css" href="<?php echo $dashboard;?>">
	<link rel="stylesheet" type="text/css" href="<?php echo $fontawsome;?>"> 

		<title>ServeWise</title>
	
</head>
<body>
	

<?php require($header); ?>
<section id='main'>
	
<?php include $main_content; 
?>
</section>
<footer>
<?php 
 require($footer);
 ?>
</footer>


<script type="text/javascript" src="<?php echo $jqurey;?>"></script>
<script type="text/javascript" src="<?php echo $aosjs;?>"></script>
<script type="text/javascript" src="<?php echo $jscript;?>"></script>

</body>

</html>