<div class="wrapper">
		<div class="row">
			<div class="col-3 col-m-6 col-sm-6">

            <h1>Add New Product</h1>
                <form action="<?php echo $controller; ?>" method="post" enctype="multipart/form-data" >
    <table width="100%">
        <tr>
            <td>Select Photo (one or multiple):</td>
            <td><input type="file" name="files[]" multiple/></td>
        </tr>
        <tr>
            <td colspan="2" align="center">Note: Supported image format: .jpeg, .jpg, .png, .gif</td>
        </tr>
        
    </table>
                     <div class="frmDronpDown">
        <div class="row">
            <label>Category:</label><br /> <select name="category"
                id="country-list" 
                onChange="getsecondlevel(this.value);">
                <option value disabled selected>Select Category</option>
<?php
foreach ($getcategories as $category) {
    ?>
<option value="<?php echo $category["category_id"]; ?>" ><?php echo $category["name"]; ?></option>
<?php
}
?>
</select>
        </div>
        <div class="row">
            <label>Second Level Category:</label><br /> <select name="secondlevel"
                id="state-list" 
                onChange="getthirdlevel(this.value);">
                <option value ="">Select Second Level</option>
            
          
            </select>
        </div>
        <div class="row">
            <label>Third Level Category:</label><br /> <select name="thirdlevel"
                id="city-list" >
                <option >Select Third Level</option>
            </select>
        </div>
    </div>
               <label>Name :</label><br>
                    <input name="name" type="text" value="" /><br>
                    <label>Description :</label><br>
                    <input name="description" type="text" value="" /><br>
                    <label>quantity :</label><br>
                    <input name="quantity" type="number" value="" /><br>
                    <label>price :</label><br>
                    <input name="price" type="number" value="" /><br>
                    <input type="submit" value="Add Product" name="add" />
                   
                </form>
        </div>
</div>
</div>
<script>
  function submitForm(form){
    
    var url = $('#form').attr("action");
    
    var formData = $('#form').serializeArray();
    $.post(url, formData).done(function (data) {
        if(data == 0){
      alert('Product is added');
    }else{
      alert('Product is not added');
    }
    });
}
</script> 
