<div class="wrapper">
		<div class="row">
			<div class="col-3 col-m-6 col-sm-6">
            <h1>Appearance</h1>
        </div>
        <div class="theme-selection">
            <div class="theme-seclection-box">
                <div class="theme-heading">Theme Name</div>
                <div class="theme-dis">Theme discribtion</div>
                <div class="theme-type">Theme Type</div>
                <div class="theme-btn">Activate</div>
            </div>
        </div>
</div>
</div>
