<!-- Datatables CSS & JS-->
	
    <link href="../vendors/datatables/css/jquery.dataTables.min.css" rel="stylesheet">
	    <link href="https://cdn.datatables.net/rowreorder/1.2.5/css/rowReorder.dataTables.min.css" rel="stylesheet">
	
	<link rel="stylesheet" href="../vendors/datatables-responsive/dataTables.responsive.css">
  <link rel="stylesheet" href="../vendors/css/vendor.bundle.base.css">
<div class="wrapper">
		<div class="row">
			<div class="col-3 col-m-6 col-sm-6">
            <h1>Category</h1>
              <label>Category name :</label>
                <form action="<?php echo $controller ?>" method="post" id="form">
                <input name="name" value="" type="text">
                <input type="button" name="addbtn" value="Add brand" onclick="submitForm()" >
        </form>
                    </div>
            <div>
            
					  <fieldset>
					  <table class="table table-bordered" id="clientstable">
					
						<thead class="bg-info">
							<th>Brand ID</th>
							<th>Brand Name</th>
                        >
							<th></th>
							<th></th>
                        </thead>
                   
					   <tbody>
						 <?php
								foreach($getbrand as $brandlist){
                           ?>
                        
						 
											
								
								<tr>
								<td><?php echo $brandlist["brand_id"]; ?></td>
								<td><?php echo $brandlist["name"]; ?></td>
								
							   </tr>
								<?php } ?>
					   </tbody>	
							
					</table>
					  </fieldset>
            </div>
            
</div>
</div>
<!-- Datatables enable script / Server side datatable-->
  <script src="../vendors/datatables/js/jquery.dataTables.min.js"></script>
  
    <script src="https://cdn.datatables.net/rowreorder/1.2.5/js/dataTables.rowReorder.min.js"></script>
    <script src="../vendors/datatables-responsive/dataTables.responsive.js"></script>

<script>
	function submitForm(form){
		
    var url = $('#form').attr("action");
		
    var formData = $('#form').serializeArray();
    $.post(url, formData).done(function (data) {
        if(data == 1){
			        alert('added');
		}else{
			alert('not added');
		}
    });
}
</script>
