	<!-- sidebar -->
	<div class="sidebar" style="overflow:scroll;">
		<ul class="sidebar-nav">
			<li class="sidebar-nav-item">
				<a href="?page=dashboard" class="sidebar-nav-link  active">
					<div>
                    <i class="fa fa-tachometer" aria-hidden="true"></i>
					</div>
					<span>
                        Dashboard  
					</span>
				</a>
				
				<ul class="sub">
					<li>
						<a href="#">
						<div class="sub-menu-inner-icon">
                    		<i class="fa fa-tachometer" aria-hidden="true"></i>
						</div>
						<div class="sub-menu-inner-title">
							user management
						</div>
						</a>
					</li>
					<li>
						<a href="#">
						<div class="sub-menu-inner-icon">
                    		<i class="fa fa-tachometer" aria-hidden="true"></i>
						</div>
						<div class="sub-menu-inner-title">
							add users
						</div>
						</a>
					</li>
					<li>
						<a href="#">
						<div class="sub-menu-inner-icon">
                    		<i class="fa fa-tachometer" aria-hidden="true"></i>
						</div>
						<div class="sub-menu-inner-title">
							view users
						</div>
						</a>
					</li>
					<li>
						<a href="#">
						<div class="sub-menu-inner-icon">
                    		<i class="fa fa-tachometer" aria-hidden="true"></i>
						</div>
						<div class="sub-menu-inner-title">
							assign user roles
						</div>
						</a>
					</li>
				</ul>
			</li>
			<li  class="sidebar-nav-item">
				<a href="?page=purchase_dashboard" class="sidebar-nav-link">
					<div>
                        <i class="fa fa-history" aria-hidden="true"></i>
					</div>
					<span>Sales</span>
				</a>
				<ul class="sub">
					<li>
						<a href="#">
						<div class="sub-menu-inner-icon">
                    		<i class="fa fa-tachometer" aria-hidden="true"></i>
						</div>
						<div class="sub-menu-inner-title">
							orders
						</div>
						</a>
					</li>
				</ul>
			</li>
			<li  class="sidebar-nav-item">
				<a href="?page=userorder_dashboard" class="sidebar-nav-link">
					<div>
                        <i class="fa fa-eye" aria-hidden="true"></i>
					</div>
					<span>Order View</span>
				</a>
				<ul class="sub">
					<li>
						<a href="#">
						<div class="sub-menu-inner-icon">
                    		<i class="fa fa-tachometer" aria-hidden="true"></i>
						</div>
						<div class="sub-menu-inner-title">
							add new product
						</div>
						</a>
					</li>
					<li>
						<a href="#">
						<div class="sub-menu-inner-icon">
                    		<i class="fa fa-tachometer" aria-hidden="true"></i>
						</div>
						<div class="sub-menu-inner-title">
							bulk import		
						</div>
						</a>
					</li>
					<li>
						<a href="#">
						<div class="sub-menu-inner-icon">
                    		<i class="fa fa-tachometer" aria-hidden="true"></i>
						</div>
						<div class="sub-menu-inner-title">
							bulk export
						</div>
						</a>
					</li>
					<li>
						<a href="#">
						<div class="sub-menu-inner-icon">
                    		<i class="fa fa-tachometer" aria-hidden="true"></i>
						</div>
						<div class="sub-menu-inner-title">
							catagory
						</div>
						</a>
					</li>
					<li>
						<a href="#">
						<div class="sub-menu-inner-icon">
                    		<i class="fa fa-tachometer" aria-hidden="true"></i>
						</div>
						<div class="sub-menu-inner-title">
							subcategory
						</div>
						</a>
					</li>
					<li>
						<a href="#">
						<div class="sub-menu-inner-icon">
                    		<i class="fa fa-tachometer" aria-hidden="true"></i>
						</div>
						<div class="sub-menu-inner-title">
							brand
						</div>
						</a>
					</li>
					<li>
						<a href="#">
						<div class="sub-menu-inner-icon">
                    		<i class="fa fa-tachometer" aria-hidden="true"></i>
						</div>
						<div class="sub-menu-inner-title">
							attibute
						</div>
						</a>
					</li>
					<li>
						<a href="#">
						<div class="sub-menu-inner-icon">
                    		<i class="fa fa-tachometer" aria-hidden="true"></i>
						</div>
						<div class="sub-menu-inner-title">
							product reviews
						</div>
						</a>
					</li>
				</ul>
            </li>
            <li class="sidebar-nav-item">
				<a href="?page=userprofile_dashboard" class="sidebar-nav-link">
					<div>
                        <i class="fa fa-user" aria-hidden="true"></i>
					</div>
					<span>Customers</span>
				</a>
				<ul class="sub">
					<li>
						<a href="#">
						<div class="sub-menu-inner-icon">
                    		<i class="fa fa-tachometer" aria-hidden="true"></i>
						</div>
						<div class="sub-menu-inner-title">
							Customer list
						</div>
						</a>
					</li>
				</ul>
			</li>
			<li  class="sidebar-nav-item">
				<a href="Catagorylist.html" class="sidebar-nav-link">
					<div>
                        <i class="fa fa-list-alt" aria-hidden="true"></i>
					</div>
					<span>Reports</span>
				</a>
				<ul class="sub">
					<li>
						<a href="#">
						<div class="sub-menu-inner-icon">
                    		<i class="fa fa-tachometer" aria-hidden="true"></i>
						</div>
						<div class="sub-menu-inner-title">
							all reports
						</div>
						</a>
					</li>
					<li>
						<a href="#">
						<div class="sub-menu-inner-icon">
                    		<i class="fa fa-tachometer" aria-hidden="true"></i>
						</div>
						<div class="sub-menu-inner-title">
							products stock
						</div>
						</a>
					</li>
					<li>
						<a href="#">
						<div class="sub-menu-inner-icon">
                    		<i class="fa fa-tachometer" aria-hidden="true"></i>
						</div>
						<div class="sub-menu-inner-title">
							product whishlist
						</div>
						</a>
					</li>
					<li>
						<a href="#">
						<div class="sub-menu-inner-icon">
                    		<i class="fa fa-tachometer" aria-hidden="true"></i>
						</div>
						<div class="sub-menu-inner-title">
							user searches
						</div>
						</a>
					</li>
				</ul>
			</li>
			<li  class="sidebar-nav-item">
				<a href="?page=productdetail_dashboard" class="sidebar-nav-link">
					<div>
                        <i class="fa fa-shopping-cart" aria-hidden="true"></i>
					</div>
					<span>Marketing</span>
				</a>
				<ul class="sub">
					<li>
						<a href="#">
						<div class="sub-menu-inner-icon">
                    		<i class="fa fa-tachometer" aria-hidden="true"></i>
						</div>
						<div class="sub-menu-inner-title">
							Flash Deals
						</div>
						</a>
					</li>
					<li>
						<a href="#">
						<div class="sub-menu-inner-icon">
                    		<i class="fa fa-tachometer" aria-hidden="true"></i>
						</div>
						<div class="sub-menu-inner-title">
							Newsletter
						</div>
						</a>
					</li>
					<li>
						<a href="#">
						<div class="sub-menu-inner-icon">
                    		<i class="fa fa-tachometer" aria-hidden="true"></i>
						</div>
						<div class="sub-menu-inner-title">
							bulk sms
						</div>
						</a>
					</li>
					<li>
						<a href="#">
						<div class="sub-menu-inner-icon">
                    		<i class="fa fa-tachometer" aria-hidden="true"></i>
						</div>
						<div class="sub-menu-inner-title">
							subscribers
						</div>
						</a>
					</li>
					<li>
						<a href="#">
						<div class="sub-menu-inner-icon">
                    		<i class="fa fa-tachometer" aria-hidden="true"></i>
						</div>
						<div class="sub-menu-inner-title">
							coupons
						</div>
						</a>
					</li>
					<li>
						<a href="#">
						<div class="sub-menu-inner-icon">
                    		<i class="fa fa-tachometer" aria-hidden="true"></i>
						</div>
						<div class="sub-menu-inner-title">
							emails
						</div>
						</a>
					</li>
				</ul>
			</li>
			<li  class="sidebar-nav-item">
				<a href="vendorbranch.html" class="sidebar-nav-link">
					<div>
                        <i class="fa fa-code-fork" aria-hidden="true"></i>
					</div>
					<span>Support</span>
				</a>
				<ul class="sub">
					<li>
						<a href="#">
						<div class="sub-menu-inner-icon">
                    		<i class="fa fa-tachometer" aria-hidden="true"></i>
						</div>
						<div class="sub-menu-inner-title">
							tickets
						</div>
						</a>
					</li>
					<li>
						<a href="#">
						<div class="sub-menu-inner-icon">
                    		<i class="fa fa-tachometer" aria-hidden="true"></i>
						</div>
						<div class="sub-menu-inner-title">
							Chats
						</div>
						</a>
					</li>
				</ul>
			</li>
			<li  class="sidebar-nav-item">
				<a href="?page=purchase_dashboard" class="sidebar-nav-link">
					<div>
                        <i class="fa fa-money" aria-hidden="true"></i>
					</div>
					<span>Setting</span>
				</a>
				<ul class="sub">
					<li>
						<a href="#">
						<div class="sub-menu-inner-icon">
                    		<i class="fa fa-tachometer" aria-hidden="true"></i>
						</div>
						<div class="sub-menu-inner-title">
							general settings
						</div>
						</a>
					</li>
					<li>
						<a href="#">
						<div class="sub-menu-inner-icon">
                    		<i class="fa fa-tachometer" aria-hidden="true"></i>
						</div>
						<div class="sub-menu-inner-title">
							features activation
						</div>
						</a>
					</li>
					<li>
						<a href="#">
						<div class="sub-menu-inner-icon">
                    		<i class="fa fa-tachometer" aria-hidden="true"></i>
						</div>
						<div class="sub-menu-inner-title">
							languages
						</div>
						</a>
					</li>
					<li>
						<a href="#">
						<div class="sub-menu-inner-icon">
                    		<i class="fa fa-tachometer" aria-hidden="true"></i>
						</div>
						<div class="sub-menu-inner-title">
							currency
						</div>
						</a>
					</li>
					<li>
						<a href="#">
						<div class="sub-menu-inner-icon">
                    		<i class="fa fa-tachometer" aria-hidden="true"></i>
						</div>
						<div class="sub-menu-inner-title">
							pickup points
						</div>
						</a>
					</li>
					<li>
						<a href="#">
						<div class="sub-menu-inner-icon">
                    		<i class="fa fa-tachometer" aria-hidden="true"></i>
						</div>
						<div class="sub-menu-inner-title">
							payment methods
						</div>
						</a>
					</li>
					<li>
						<a href="#">
						<div class="sub-menu-inner-icon">
                    		<i class="fa fa-tachometer" aria-hidden="true"></i>
						</div>
						<div class="sub-menu-inner-title">
							smtp settings
						</div>
						</a>
					</li>
					<li>
						<a href="#">
						<div class="sub-menu-inner-icon">
                    		<i class="fa fa-tachometer" aria-hidden="true"></i>
						</div>
						<div class="sub-menu-inner-title">
							social media link
						</div>
						</a>
					</li>
					<li>
						<a href="#">
						<div class="sub-menu-inner-icon">
                    		<i class="fa fa-tachometer" aria-hidden="true"></i>
						</div>
						<div class="sub-menu-inner-title">
						shipping configuration
						</div>
						</a>
					</li>
				</ul>
			</li>
		</ul>
	</div>
	<!-- end sidebar -->