	<!-- sidebar -->
	<div class="sidebar">
		<ul class="sidebar-nav">
			<li class="sidebar-nav-item">
				<a href="../View/userdashboard.php" class="sidebar-nav-link  active">
					<div>
                    <i class="fa fa-tachometer" aria-hidden="true"></i>
					</div>
					<span>
                        Dashboard  
					</span>
				</a>
			</li>
			<li  class="sidebar-nav-item">
				<a href="../View/purchase.php" class="sidebar-nav-link">
					<div>
                        <i class="fa fa-history" aria-hidden="true"></i>
					</div>
					<span>Purchase History</span>
				</a>
			</li>
			<li  class="sidebar-nav-item">
				<a href="../View/userorder.php" class="sidebar-nav-link">
					<div>
                        <i class="fa fa-eye" aria-hidden="true"></i>
					</div>
					<span>Order View</span>
				</a>
            </li>
            <li class="sidebar-nav-item">
				<a href="vendorprofile.html" class="sidebar-nav-link">
					<div>
                        <i class="fa fa-user" aria-hidden="true"></i>
					</div>
					<span>User Profile</span>
				</a>
			</li>
			<li  class="sidebar-nav-item">
				<a href="Catagorylist.html" class="sidebar-nav-link">
					<div>
                        <i class="fa fa-list-alt" aria-hidden="true"></i>
					</div>
					<span>Catgegory list</span>
				</a>
			</li>
			<li  class="sidebar-nav-item">
				<a href="vendorproduct.html" class="sidebar-nav-link">
					<div>
                        <i class="fa fa-shopping-cart" aria-hidden="true"></i>
					</div>
					<span>Products</span>
				</a>
			</li>
			<li  class="sidebar-nav-item">
				<a href="vendorbranch.html" class="sidebar-nav-link">
					<div>
                        <i class="fa fa-code-fork" aria-hidden="true"></i>
					</div>
					<span>Branch</span>
				</a>
            </li>
			<li  class="sidebar-nav-item">
				<a href="productview.html" class="sidebar-nav-link">
					<div>
                        <i class="fa fa-money" aria-hidden="true"></i>
					</div>
					<span>Purchas Product</span>
				</a>
			</li>
			<li  class="sidebar-nav-item">
				<a href="cart.html" class="sidebar-nav-link">
					<div>
                        <i class="fa fa-credit-card-alt" aria-hidden="true"></i>
					</div>
					<span>Cart</span>
				</a>
			</li>
			
		</ul>
	</div>
	<!-- end sidebar -->