
	  <?php require $footer;?>	
	<!-- main content -->
	<div class="wrapper">
		<div class="row">
			<div class="col-12 col-m-12 col-sm-12">
				<div class="container-content">
					
                    <div class="user-profile-dis">
                        
                    <form action="<?php echo $controller ?>" method="post" id="form">
						<div class="user-detail1">
                            <label>Name.</label>
                            <input name="name" type="text" >
                           
                            <label>contact No.</label>
                            <input name="contactno" type="number" >
							 <label>email id.</label>
                            <input name="email" type="text" >
                        </div>
                        <div class="user-detail1">
                            <label>Address.</label>
                            <input name="address" type="text" >
                            <label>Address2.</label>
                            <input name="address2" type="text" >
                           
							
                        </div >
						
						<div class="user-detail1">
							<input type="button" name="signupbtn" value="Request" onclick="submitForm()">
						</div>
						</form>
                    </div>
                </div>
			</div>		
		</div>
	</div>
	<!-- end main content -->
<script>
  function submitForm(form){
    
    var url = $('#form').attr("action");
    
    var formData = $('#form').serializeArray();
    $.post(url, formData).done(function (data) {
        if(data == 1){
      alert('added');
    }else{
      alert('error');
    }
    });
}
</script> 