
	  <?php require $footer;?>	
	<!-- main content -->
	<div class="wrapper">
		<div class="row">
			<div class="col-12 col-m-12 col-sm-12">
				<div class="container-content">
					
                    <div class="user-profile-dis">
                        
                    <form action="<?php echo $controller ?>" method="post" id="form">
						<div class="user-detail1">
                            <label>Name.</label>
                            <input name="name" type="text" >
                           
                            <label>contact No.</label>
                            <input name="contactno" type="number" >
							 <label>email id.</label>
                            <input name="email" type="text" >
                        </div>
                        <div class="user-detail1">
                            <label>Address.</label>
                            <input name="address" type="text" >
                            <label>Address2.</label>
                            <input name="address2" type="text" >
                            
					<div class="frmDronpDown">
        <div class="row">
            <label>Country:</label><br /> <select name="country"
                id="country-list" 
                onChange="getState(this.value);">
                <option value disabled selected>Select Country</option>
<?php
foreach ($getcountries as $country) {
    ?>
<option value="<?php echo $country["id"]; ?>" ><?php echo $country["name"]; ?></option>
<?php
}
?>
</select>
        </div>
        <div class="row">
            <label>State:</label><br /> <select name="state"
                id="state-list" 
                onChange="getCity(this.value);">
                <option value="">Select State</option>
          
            </select>
        </div>
        <div class="row">
            <label>City:</label><br /> <select name="city"
                id="city-list" >
                <option>Select City</option>
            </select>
        </div>
    </div>		
                        </div >
						
						<div class="user-detail1">
							<input type="button" name="signupbtn" value="Request" onclick="submitForm()">
						</div>
						</form>
                    </div>
                </div>
			</div>		
		</div>
	</div>
	<!-- end main content -->
<script>
  function submitForm(form){
    
    var url = $('#form').attr("action");
    
    var formData = $('#form').serializeArray();
    $.post(url, formData).done(function (data) {
        if(data == 1){
      alert('added');
    }else{
      alert('error');
    }
    });
}

</script> 
