<!DOCTYPE html>
<html>
<head>
	<title>SW Admin</title>

	<meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0">
	<link rel="icon" type="image/png" href="assets/favicon icon nazreen.jpg"/>

	<!-- Import lib -->
	<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.css">
	<link rel="stylesheet" type="text/css" href="fontawesome-free/css/all.min.css">
	<link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
	<!-- End import lib -->

	<link rel="stylesheet" type="text/css" href="style.css">
</head>
<body class="overlay-scrollbar">
	<!-- navbar -->
	<div class="navbar">
		<!-- nav left -->
		<ul class="navbar-nav">
			<li class="nav-item">
				<a class="nav-link">
					<i class="fas fa-bars" onclick="collapseSidebar()">
					</i>
				</a>
			</li>
			<li class="nav-item">
				<img src="assets/nazreen logo web.png" alt="Admin logo" class="logo logo-light">
				<img src="assets/nazreen logo white web.png" alt="Admin logo" class="logo logo-dark">
			</li>
		</ul>
		<!-- end nav left -->
		<!-- form -->
		<form class="navbar-search">
			<input type="text" name="Search" class="navbar-search-input" placeholder="What you looking for...">
			<i class="fas fa-search"></i>
		</form>
		<!-- end form -->
		<!-- nav right -->
		<ul class="navbar-nav nav-right">
			<li class="nav-item mode">
				<a class="nav-link" href="#" onclick="switchTheme()">
					<i class="fas fa-moon dark-icon"></i>
					<i class="fas fa-sun light-icon"></i>
				</a>
			</li>
			<li class="nav-item dropdown">
				<a class="nav-link">
					<i class="fas fa-bell dropdown-toggle" data-toggle="notification-menu"></i>
					<span class="navbar-badge">2</span>
				</a>
				<ul id="notification-menu" class="dropdown-menu notification-menu">
					<div class="dropdown-menu-header">
						<span>
							Notifications
						</span>
					</div>
					<div class="dropdown-menu-content overlay-scrollbar scrollbar-hover">
						<li class="dropdown-menu-item">
							<a href="#" class="dropdown-menu-link">
								<div>
									<i class="fas fa-gift"></i>
								</div>
								<span>
									Nazreen Consulting Demo.
									<br>
									<span>
										23/10/2020
									</span>
								</span>
							</a>
						</li>
						<li class="dropdown-menu-item">
							<a href="#" class="dropdown-menu-link">
								<div>
									<i class="fas fa-tasks"></i>
								</div>
								<span>
									Nazreen Consulting Demo.
									<br>
									<span>
										23/10/2020
									</span>
								</span>
							</a>
						</li>
					</div>
					<div class="dropdown-menu-footer">
						<span>
							View all notifications
						</span>
					</div>
				</ul>
			</li>
			<li class="nav-item avt-wrapper">
				<div class="avt dropdown">
					<img src="assets/Muzzamil.jpg" alt="User image" class="dropdown-toggle" data-toggle="user-menu">
					<ul id="user-menu" class="dropdown-menu">
						<li  class="dropdown-menu-item">
							<a class="dropdown-menu-link">
								<div>
									<i class="fas fa-user-tie"></i>
								</div>
								<span>Profile</span>
							</a>
						</li>
						<li  class="dropdown-menu-item">
							<a href="#" class="dropdown-menu-link">
								<div>
									<i class="fas fa-sign-out-alt"></i>
								</div>
								<span>Logout</span>
							</a>
						</li>
					</ul>
				</div>
			</li>
		</ul>
		<!-- end nav right -->
	</div>
	<!-- end navbar -->
		<!-- sidebar -->
	<div class="sidebar">
		<ul class="sidebar-nav">
			<li class="sidebar-nav-item">
					<a href="../View/userdashboard.php" class="sidebar-nav-link  active">
					<div>
						<i class="fas fa-tachometer-alt"></i>
					</div>
					<span>
						Dashboard
					</span>
				</a>
			</li>
			<li class="sidebar-nav-item">
				<a href="../View/userprofile.php" class="sidebar-nav-link">
					<div>
						<i class="fab fa-sellsy"></i>
					</div>
					<span>User Profile</span>
				</a>
			</li>
			<li  class="sidebar-nav-item">
				<a href="../View/purchase.php" class="sidebar-nav-link">
					<div>
						<i class="fas fa-search-dollar"></i>
					</div>
					<span>Purchase History</span>
				</a>
			</li>
			<li  class="sidebar-nav-item">
				<a href="../View/userorder.php" class="sidebar-nav-link">
					<div>
						<i class="fas fa-file"></i>
					</div>
					<span>Order View</span>
				</a>
			</li>
			
		</ul>
	</div>
	<!-- end sidebar -->
	<!-- main content -->
	<div class="wrapper">
		<div class="row">
			<div class="col-12 col-m-12 col-sm-12">
				<div class="card">
					<div class="card-header">
						<h3>
							Table
						</h3>
						<i class="fas fa-ellipsis-h"></i>
					</div>
					<div class="card-content">
						<table>
							<thead>
								<tr>
									<th>#</th>
									<th>Product Name</th>
									<th>Price</th>
									<th>Quantity</th>
									<th>Order Time</th>
									<th>Order Date</th>
									<th>Order Status</th>
								</tr>
							</thead>
							<tbody>
								<tr>
									<td>1</td>
									<td>Shirt</td>
									<td>
										<span>$</span>20
										
									</td>
									<td>2</td>
									<td>07:00 A.M</td>
                                    <td>10/12/2020</td>
                                    <td><span class="dot">
                                        <i class="bg-success"></i>
                                        Completed
                                    </span></td>
                                </tr>
                                <tr>
									<td>1</td>
									<td>Shirt</td>
									<td>
										<span>$</span>20
										
									</td>
									<td>2</td>
									<td>07:00 A.M</td>
                                    <td>10/12/2020</td>
                                    <td><span class="dot">
                                        <i class="bg-warning"></i>
                                        In progress
                                    </span></td>
                                </tr>
                                <tr>
									<td>1</td>
									<td>Shirt</td>
									<td>
										<span>$</span>20
										
									</td>
									<td>2</td>
									<td>07:00 A.M</td>
                                    <td>10/12/2020</td>
                                    <td><span class="dot">
                                        <i class="bg-primary"></i>
                                        Pending
                                    </span></td>
                                </tr>
                                <tr>
									<td>1</td>
									<td>Shirt</td>
									<td>
										<span>$</span>20
										
									</td>
									<td>2</td>
									<td>07:00 A.M</td>
                                    <td>10/12/2020</td>
                                    <td>										<span class="dot">
                                        <i class="bg-danger"></i>
                                        Delayed
                                    </span></td>
                                </tr>
							</tbody>
						</table>
					</div>
				</div>
			</div>		
		</div>
	</div>
	<!-- end main content -->
	<!-- import script -->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js"></script>
	<script src="index.js"></script>
	<!-- end import script -->
</body>
</html>